package cn.jbg.cmab.bean;

import java.math.BigDecimal;

public class Item {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_id
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_name
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_price
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    private BigDecimal itemPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_img
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    private String itemImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_sales
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    private Integer itemSales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_inventory
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    private Integer itemInventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_desc
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    private String itemDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_rate
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    private Integer itemRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_id
     *
     * @return the value of item.item_id
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_id
     *
     * @param itemId the value for item.item_id
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_name
     *
     * @return the value of item.item_name
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_name
     *
     * @param itemName the value for item.item_name
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_price
     *
     * @return the value of item.item_price
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    public BigDecimal getItemPrice() {
        return itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_price
     *
     * @param itemPrice the value for item.item_price
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    public void setItemPrice(BigDecimal itemPrice) {
        this.itemPrice = itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_img
     *
     * @return the value of item.item_img
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    public String getItemImg() {
        return itemImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_img
     *
     * @param itemImg the value for item.item_img
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    public void setItemImg(String itemImg) {
        this.itemImg = itemImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_sales
     *
     * @return the value of item.item_sales
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    public Integer getItemSales() {
        return itemSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_sales
     *
     * @param itemSales the value for item.item_sales
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    public void setItemSales(Integer itemSales) {
        this.itemSales = itemSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_inventory
     *
     * @return the value of item.item_inventory
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    public Integer getItemInventory() {
        return itemInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_inventory
     *
     * @param itemInventory the value for item.item_inventory
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    public void setItemInventory(Integer itemInventory) {
        this.itemInventory = itemInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_desc
     *
     * @return the value of item.item_desc
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    public String getItemDesc() {
        return itemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_desc
     *
     * @param itemDesc the value for item.item_desc
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    public void setItemDesc(String itemDesc) {
        this.itemDesc = itemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_rate
     *
     * @return the value of item.item_rate
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    public Integer getItemRate() {
        return itemRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_rate
     *
     * @param itemRate the value for item.item_rate
     *
     * @mbggenerated Sun Mar 18 20:31:02 CST 2018
     */
    public void setItemRate(Integer itemRate) {
        this.itemRate = itemRate;
    }
}