package cn.jbg.cmab.bean;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.username
     *
     * @mbggenerated Wed Feb 07 17:28:41 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.passwords
     *
     * @mbggenerated Wed Feb 07 17:28:41 CST 2018
     */
    private String passwords;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.username
     *
     * @return the value of users.username
     *
     * @mbggenerated Wed Feb 07 17:28:41 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.username
     *
     * @param username the value for users.username
     *
     * @mbggenerated Wed Feb 07 17:28:41 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.passwords
     *
     * @return the value of users.passwords
     *
     * @mbggenerated Wed Feb 07 17:28:41 CST 2018
     */
    public String getPasswords() {
        return passwords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.passwords
     *
     * @param passwords the value for users.passwords
     *
     * @mbggenerated Wed Feb 07 17:28:41 CST 2018
     */
    public void setPasswords(String passwords) {
        this.passwords = passwords;
    }

    @Override
    public String toString() {
        return "Users{" +
                "username='" + username + '\'' +
                ", passwords='" + passwords + '\'' +
                '}';
    }
}